set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'mhinz/vim-signify'
Plugin 'zenorocha/dracula-theme'
Plugin 'davidhalter/jedi-vim'
Plugin 'nvie/vim-flake8'
Plugin 'elixir-editors/vim-elixir'
Plugin 'slashmili/alchemist.vim'
Plugin 'ntpeters/vim-better-whitespace'

call vundle#end()

set ruler
set showcmd
set autoindent
set cursorline
set nocursorcolumn
set nocursorline
set laststatus=2
set encoding=utf-8
set tabstop=2
set foldmethod=indent
set foldlevel=99
set backspace=indent,eol,start
set tabstop=2 shiftwidth=2 expandtab

syntax on
syntax sync minlines=256

filetype plugin indent on
autocmd Filetype sh setlocal sts=2 sw=2 expandtab
autocmd Filetype javascript setlocal sts=2 sw=2 expandtab
autocmd Filetype css setlocal sts=2 sw=2 expandtab
autocmd Filetype sql setlocal sts=2 sw=2 expandtab
autocmd Filetype lua setlocal sts=2 sw=2 expandtab
autocmd Filetype scss setlocal sts=2 sw=2 expandtab
autocmd Filetype html setlocal sts=2 sw=2 expandtab
autocmd Filetype python setlocal sts=4 sw=4 expandtab
autocmd Filetype c setlocal sts=4 sw=4 expandtab
autocmd Filetype cpp setlocal sts=4 sw=4 expandtab
autocmd Filetype json setlocal sts=4 sw=4 expandtab
autocmd Filetype go setlocal sts=2 sw=2 expandtab
autocmd Filetype vue setlocal sts=2 sw=2 expandtab
autocmd Filetype yml setlocal sts=2 sw=2 expandtab

" Custom key bindings
nnoremap <C-W>M <C-W>\| <C-W>_  " maximize buffer
nnoremap <C-W>m <C-W>=  " minimize buffer

let g:ctrlp_custom_ignore = {
  \ 'dir': 'node_modules\|DS_Store\|git',
  \ 'file': '\v\.(pyc|lock|orig|npm)$'
  \ }

let g:airline_powerline_fonts = 1
let g:airline_exclude_preview=1

let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
