set nocompatible
filetype off

call plug#begin('~/.vim/plugged')
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'junegunn/fzf.vim'
  Plug 'mhinz/vim-signify', { 'branch': 'legacy' }
  Plug 'mattn/emmet-vim'
  Plug 'pangloss/vim-javascript'
  Plug 'mxw/vim-jsx'
  Plug 'dense-analysis/ale'
  Plug 'skywind3000/asyncrun.vim'
  Plug 'prettier/vim-prettier', { 'do': 'npm install' }
call plug#end()

set ruler
set showcmd
set autoindent
set cursorline
set nocursorcolumn
set nocursorline
set laststatus=2
set encoding=utf-8
set tabstop=2
set foldmethod=indent
set foldlevel=99
set backspace=indent,eol,start
set tabstop=2 shiftwidth=2 expandtab

syntax on
syntax sync minlines=256

filetype plugin indent on
autocmd Filetype sh setlocal sts=2 sw=2 expandtab
autocmd Filetype javascript setlocal sts=2 sw=2 expandtab
autocmd Filetype css setlocal sts=2 sw=2 expandtab
autocmd Filetype sql setlocal sts=2 sw=2 expandtab
autocmd Filetype lua setlocal sts=2 sw=2 expandtab
autocmd Filetype scss setlocal sts=2 sw=2 expandtab
autocmd Filetype html setlocal sts=2 sw=2 expandtab
autocmd Filetype python setlocal sts=4 sw=4 expandtab
autocmd Filetype c setlocal  softtabstop=4 shiftwidth=4 tabstop=4 noet
autocmd Filetype cpp setlocal sts=4 sw=4 expandtab
autocmd Filetype json setlocal sts=4 sw=4 expandtab
autocmd Filetype go setlocal sts=2 sw=2 expandtab
autocmd Filetype vue setlocal sts=2 sw=2 expandtab
autocmd Filetype yml setlocal sts=2 sw=2 expandtab

nnoremap <C-p> :Files<Cr>

let g:user_emmet_settings = {
  \  'javascript.jsx' : {
    \      'extends' : 'jsx',
    \  },
  \}

autocmd BufWritePost *.js AsyncRun -post=checktime eslint --fix
autocmd BufWritePost *.js PrettierAsync
